#!/usr/bin/env bash
# Display listening ports with PID and program name

# Check if the script is run with sudo
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Display listening ports with PID and program name
netstat -tulnp