#!/usr/bin/env bash
# Script to change localhost and facebook.com IP resolutions

sudo cp /etc/hosts /etc/hosts.backup

# Modify /etc/hosts to resolve localhost to 127.0.0.2 and facebook.com to 8.8.8.8
# Check if the localhost entry already exists and modify it, otherwise add it
if grep -q "127.0.0.2 localhost" /etc/hosts; then
    echo "localhost is already set to 127.0.0.2"
else
    if grep -q "127.0.0.1 localhost" /etc/hosts; then
        sudo sed -i '' 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts
    else
        sudo sed -i '' 's/127.0.0.1/127.0.0.2/' /etc/hosts
        echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
    fi
fi

# Check if the facebook.com entry already exists and modify it, otherwise add it
if grep -q "8.8.8.8 facebook.com" /etc/hosts; then
    echo "facebook.com is already set to 8.8.8.8"
else
    if grep -q "facebook.com" /etc/hosts; then
        sudo sed -i '' 's/.* facebook.com/8.8.8.8 facebook.com/' /etc/hosts
    else
        echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
    fi
fi
